//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 08:10:25 AM CEST 
//


package nl.mikero.turntopassage.core.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TwStories_QNAME = new QName("", "tw-storiesdata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TwStoriesdata }
     * 
     */
    public TwStoriesdata createTwStoriesdata() {
        return new TwStoriesdata();
    }

    /**
     * Create an instance of {@link TwStorydata }
     * 
     */
    public TwStorydata createTwStorydata() {
        return new TwStorydata();
    }

    /**
     * Create an instance of {@link TwPassagedata }
     * 
     */
    public TwPassagedata createTwPassagedata() {
        return new TwPassagedata();
    }

    /**
     * Create an instance of {@link Style }
     * 
     */
    public Style createStyle() {
        return new Style();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TwStoriesdata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tw-storiesdata")
    public JAXBElement<TwStoriesdata> createTwStories(TwStoriesdata value) {
        return new JAXBElement<TwStoriesdata>(_TwStories_QNAME, TwStoriesdata.class, null, value);
    }

}
